Volatile

diff --git a/board/raspberryradio/mksdcard b/board/raspberryradio/mksdcard
--- a/board/raspberryradio/mksdcard
+++ b/board/raspberryradio/mksdcard
@@ -80,11 +80,11 @@ fi
 
 # sanity check
 
-if [ ! -d "images/rpi-firmware" ] || [ ! -f "images/rootfs.tar" ]; then
-	if [ -d "output/images/rpi-firmware" ] && [ -f "output/images/rootfs.tar" ]; then
+if [ ! -d "images/rpi-firmware" ]; then
+	if [ -d "output/images/rpi-firmware" ]; then
 		OUTPUT_PREFIX="output/"
 	else
-		echo "Didn't find boot and/or rootfs.tar! ABORT."
+		echo "Didn't find boot! ABORT."
 		exit 1
 	fi
 fi
@@ -103,7 +103,7 @@ n
 p
 1
 
-+32M
++100M
 n
 p
 2
@@ -143,12 +143,12 @@ sync
 
 # fill rootfs
 
-section "Populating rootfs partition..."
+#section "Populating rootfs partition..."
 
-mount "${SDCARD}2" .mnt || exit 2
-${TAR} -xpsf ${OUTPUT_PREFIX}images/rootfs.tar -C .mnt
-umount .mnt
-sync
+#mount "${SDCARD}2" .mnt || exit 2
+#${TAR} -xpsf ${OUTPUT_PREFIX}images/rootfs.tar -C .mnt
+#umount .mnt
+#sync
 
 # clean up
 
